export type AlgorithmFamily = {
  slug: string;
  name: string;
  variants: number;
  instruments: string;
  notes: string;
  ids: string[];
};

export const instruments = [
  { code: "NQ", name: "Nasdaq 100 Futures", exchange: "CME" },
  { code: "ES", name: "S&P 500 Futures", exchange: "CME" },
  { code: "GC", name: "Gold Futures", exchange: "COMEX" },
  { code: "CL", name: "Crude Oil Futures", exchange: "NYMEX" },
  { code: "YM", name: "Dow Jones Futures", exchange: "CBOT" },
  { code: "NKD", name: "Nikkei 225 Futures", exchange: "CME" },
  { code: "BTC", name: "Bitcoin", exchange: "Crypto" },
  { code: "ETH", name: "Ethereum", exchange: "Crypto" },
];

export const families: AlgorithmFamily[] = [
  {
    slug: "raptor",
    name: "Raptor",
    variants: 11,
    instruments: "NQ, ES, GC, CL, BTC, ETH, NKD, YM",
    notes: "Includes ES V2/V3 and NQ 22-minute",
    ids: [
      "ESRAPTOR",
      "ESRAPTORV2",
      "ESRAPTORV3",
      "NQRAPTOR",
      "NQRAPTOR22",
      "GCRAPTOR",
      "CLRAPTOR",
      "YMRAPTOR",
      "NKDRAPTOR",
      "BTCRAPTOR",
      "ETHRAPTOR",
    ],
  },
  {
    slug: "blaze",
    name: "Blaze",
    variants: 6,
    instruments: "NQ, GC, NKD",
    notes: "V3 is prop-firm ready; others hold overnight",
    ids: ["NQBLAZE", "NQBLAZEV3", "GCBLAZE", "GCBLAZEV3", "NKDBLAZE", "NKDBLAZEV3"],
  },
  {
    slug: "spark",
    name: "Spark",
    variants: 3,
    instruments: "NQ, GC",
    notes: "Includes NQ V2",
    ids: ["NQSPARK", "NQSPARKV2", "GCSPARK"],
  },
  {
    slug: "volt",
    name: "Volt",
    variants: 4,
    instruments: "NQ, ES",
    notes: "Includes V2",
    ids: ["NQVOLT", "NQVOLTV2", "ESVOLT", "ESVOLTV2"],
  },
  {
    slug: "core",
    name: "Core",
    variants: 1,
    instruments: "ES",
    notes: "Overnight / non-prop",
    ids: ["ESCORE"],
  },
  {
    slug: "strike",
    name: "Strike",
    variants: 1,
    instruments: "GC",
    notes: "Deprecated",
    ids: ["GCSTRIKE"],
  },
  {
    slug: "bro",
    name: "Bro",
    variants: 1,
    instruments: "ES",
    notes: "",
    ids: ["ESBRO"],
  },
  {
    slug: "pag",
    name: "Pag",
    variants: 1,
    instruments: "ES",
    notes: "",
    ids: ["ESPAG"],
  },
  {
    slug: "don",
    name: "Don",
    variants: 2,
    instruments: "NQ, ES",
    notes: "NQ Don is beta",
    ids: ["NQDON", "ESDON"],
  },
  {
    slug: "gray",
    name: "Gray",
    variants: 2,
    instruments: "NQ",
    notes: "Includes V2",
    ids: ["NQGRAY", "NQGRAYV2"],
  },
  {
    slug: "surge",
    name: "Surge",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQSURGE"],
  },
  {
    slug: "pulse",
    name: "Pulse",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQPULSE"],
  },
  {
    slug: "beast",
    name: "Beast",
    variants: 1,
    instruments: "NQ",
    notes: "Beta",
    ids: ["NQBEAST"],
  },
  {
    slug: "pow",
    name: "Pow",
    variants: 2,
    instruments: "NQ, GC",
    notes: "",
    ids: ["NQPOW", "GCPOW"],
  },
  {
    slug: "vix",
    name: "Vix",
    variants: 2,
    instruments: "NQ, GC",
    notes: "",
    ids: ["NQVIX", "GCVIX"],
  },
  {
    slug: "bliss",
    name: "Bliss",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQBLISS"],
  },
  {
    slug: "helix",
    name: "Helix",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQHELIX"],
  },
  {
    slug: "vex",
    name: "Vex",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQVEX"],
  },
  {
    slug: "alpha",
    name: "Alpha",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQALPHA"],
  },
  {
    slug: "lzma",
    name: "Lzma",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQLZMA"],
  },
  {
    slug: "markov",
    name: "Markov",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQMARKOV"],
  },
  {
    slug: "dyr",
    name: "Dyr",
    variants: 2,
    instruments: "NQ, GC",
    notes: "",
    ids: ["NQDYR", "GCDYR"],
  },
  {
    slug: "bix",
    name: "Bix",
    variants: 1,
    instruments: "NQ",
    notes: "",
    ids: ["NQBIX"],
  },
  {
    slug: "rse",
    name: "Rse",
    variants: 1,
    instruments: "ES",
    notes: "",
    ids: ["ESRSE"],
  },
  {
    slug: "marcon",
    name: "Marcon",
    variants: 1,
    instruments: "NQ",
    notes: "Overnight",
    ids: ["NQMARCON"],
  },
  {
    slug: "lon",
    name: "Lon",
    variants: 1,
    instruments: "NQ",
    notes: "Overnight",
    ids: ["NQLON"],
  },
  {
    slug: "nox",
    name: "Nox",
    variants: 1,
    instruments: "NQ",
    notes: "Overnight",
    ids: ["NQNOX"],
  },
  {
    slug: "ms",
    name: "Ms",
    variants: 1,
    instruments: "NQ",
    notes: "Beta",
    ids: ["NQMS"],
  },
];
